name: Shank Server Test CI-CD

on:
  push:
    branches: [ test ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
  CD:
    needs: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t leaguelugas/shank:dev .

      - name: Publish To Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: leaguelugas/shank:dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}